### ISSUE TITLE
Mvn Central Where?

### ISSUE THREAD

**Issue by cobbce** [palantir/encrypted-config-value#173]
## What happened?

I attempted to add this lib to my mvn dependencies and I expected it to retrieve the library.

Instead, I discovered that this is only made available in jcenter. In 10 years I have never been required to add a new mvn package repository to add a dependency. This raises the question.... why?

**Comment by surbhim13** [comment]
Looks like JCenter and Bintray are getting closed down. 
https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/
Is this being moved to Maven Central soon? @asvoboda : Maybe you can help here?

**Comment by asvoboda** [comment]
Looks like our bot got tripped up by CI: https://github.com/palantir/encrypted-config-value/pull/179. Will take a look, since we have moved most of our publishing already to maven central. Thanks for the heads up!

**Comment by surbhim13** [comment]
@asvoboda : Thank you!

**Comment by asvoboda** [comment]
As of [2.2.0](https://github.com/palantir/encrypted-config-value/releases/tag/2.2.0) we're publishing to maven central.
