### ISSUE TITLE
Make the key location changeable via config

### ISSUE THREAD

**Issue by briantoth** [palantir/encrypted-config-value#18]
right now you either need to use a system property or accept the default (https://github.com/palantir/encrypted-config-value/blob/a1a5dc5b2de92219b80dd9f093fef05e4fb1a5c2/encrypted-config-value/src/main/java/com/palantir/config/crypto/KeyPair.java#L78).  my preference would be to set this value in a config file, but I am unfamiliar with the dropwizard bootstrapping process (would this introduce a sort of circular dependency in which you need e-c-v to read your config file but need your config file to run e-c-v?).  thoughts?

**Comment by markelliot** [comment]
I don't think you can read a config file in the place that we're injecting this change. What's wrong with using a convention based location for the key?

**Comment by ash211** [comment]
@briantoth ping?

**Comment by briantoth** [comment]
we've handled this in the go version of e-c-v by adopting the java default.  i don't think it is valuable to pursue this further given the complications with trying to define this value in config itself.
