### ISSUE TITLE
AEADBadTagException: Tag mismatch!

### ISSUE THREAD

**Issue by cjr8020** [palantir/encrypted-config-value#25]
Hey guys,
After patching Oracle JDK 1.8 to a more recent patch, I started getting
`javax.crypto.AEADBadTagException: Tag mismatch!`
I saw your note on reverting back to Java 7 compatibility and bouncycastle provider recommendation.
I added bouncycastle provider just before configuring EncryptedConfigValueBundle
`Security.addProvider(new BouncyCastleProvider());`
but I'm unable to resolve the "Tag mismatch" error. 
Any ideas, please?
Thanks

**Comment by markelliot** [comment]
What version of Java 8 are you running?

**Comment by cjr8020** [comment]
Needed to replace OpenJDK with Oracle JDK.  Went first to 1.8 65, then 77.
Managed to resolve the issue - turns out as I needed to regenerate the key and all the encrypted values, I missed something (and I had a few in my config).

However, I am curious whether in your testing including this 
`Security.addProvider(new BouncyCastleProvider());`
would be sufficient to bring BouncyCastle as provider?

Thanks again

**Comment by markelliot** [comment]
We're not currently testing the BouncyCastle supplier setup, sorry.

Glad you managed to resolve the issue in your setup.

**Comment by cjr8020** [comment]
Thanks Mark!

**Comment by NobodyYouKnow01** [comment]
Hey, how exactly do you go about changing over to OracleJDK?
