### ISSUE TITLE
Abstractions for KeyPair and Algorithm make code hard to work with

### ISSUE THREAD

**Issue by nmiyake** [palantir/encrypted-config-value#61]
We may end up closing as "won't fix", but documenting this since I have to re-learn these quirks every time I try to make changes or ports of this library.

They way in which `encrypted-config-value` stores and reads keys has a lot of magic and hard-coding that makes it hard to cleanly abstract/separate things like storage versus implementation of keys and algorithms. We have it take the following over-all shape:

* There's a `KeyPair` that holds a public key (always populated) and private key (only populated if the algorithm is asymmetric)
* The key serialization format is `<algorithm>:<base64-encoded-key>`, where `<algorithm>` can be `AES` or `RSA`
* If the format is `RSA`, the `<base64-encoded-key>` is either the public key encoded in X509 or the private key encoded in PKCS8
  * There is no way to distinguish between the two

Right now, loading keys works as follows:

* `KeyPair.fromDefaultPath` examines a pre-determined location (based on environment variable or hard-coded constant) for a key file (and `KeyPair.fromPath` examines a user-specified path), and treats this as the "public" key. It effectively reads/loads the serialized form, but doesn't actually resolve it to a "real" algorithm
* As part of the loading logic, the logic checks to see if a file that ends in `.private` exists alongside the default (or specified) file
  * If it does, then it loads that file as the "private" key (again, only loads serialized form and does not resolve)
* When doing decryption, checks to see if the key pair has a private key -- if it does, uses that, otherwise, uses the public key (assumes symmetric)
* The decryption logic itself will receive the "serialized" key, and will instantiate it into its expected algorithm -- for AES, it reads and resolves as an AES key, while for RSA, it reads it as an RSA private key

This approach relies on a lot of shared conventions and previous steps, which makes it hard to abstract the logic. For example, if you have `RSA:<encoded-content>`, there's no way to know if that is for a private or public key -- the file is read based on conventions, stored in another object that maintains it, and then at the very end the user decides how to resolve it (the "decrypt" method for RSA says "hey, I got a serialized key, so I'm going to read it as an RSA private key"). There's also a conflation of logic between symmetric and asymmetric keys.

I think there is one concrete change that would make a lot of the concepts here cleaner:

* Serialization format for keys should be unique
  * Having something like `RSA-public:<key>` and `RSA-private:<key>` would allow the key type to be determined unambiguously from the serialized form (instead of relying on where the files were initially placed and following that logic throughout)

We could maintain back-compat by keeping the current logic if plain `RSA:` is found, but using more specific logic otherwise.

Realistically, this change may never happen, but at least this issue can be a reference for figuring out how the abstractions currently work.

**Comment by markelliot** [comment]
I think this is basically the same problem we're trying to address in #56. What's required is a backwards-compatible format change, and as on the PR, I'm interested in having something that is future-proof rather than repeating the convention driven approach.

**Comment by nmiyake** [comment]
OK great. However, note that that PR currently only addresses AES keys -- to address this issue, we would want to also make a similar change for RSA keys (so that we could distinguish public versus private and possibly encode further information like key size)

**Comment by markelliot** [comment]
Yep, all the things can get less conventiony.

**Comment by nmiyake** [comment]
Closing this mega-issue and open more targeted ones.
