### ISSUE TITLE
Equality doesn't work as expected for KeyWithType 

### ISSUE THREAD

**Issue by dubstack** [palantir/encrypted-config-value#91]
```
        // publicKeyPath is an arbitrary Path
        KeyFileUtils.keyWithTypeToFile(RSA_ALGORITHM.newKeyPair().encryptionKey(), publicKeyPath);

        KeyWithType publicKey = KeyFileUtils.keyWithTypeFromPath(publicKeyPath);

        assertThat(publicKey.getKey(), is(generatedKeyPair.encryptionKey().getKey()));

```
The above fails as the Equals function is not overriden. 

We can either use Immutables or override the equals method in our implementations of the Key interface. 

@bavardage @nmiyake Would be happy to send out a PR if we agree on one of the suggested fix.

**Comment by nmiyake** [comment]
It's probably reasonable for `KeyWithType` to implement `equals`. I think the most sensible thing would be for `KeyWithType` to support equality and for it to use its Strings representation (which is already used as its JSON value: https://github.com/palantir/encrypted-config-value/blob/develop/encrypted-config-value/src/main/java/com/palantir/config/crypto/KeyWithType.java#L42).

It already uses Immutables, so just be a matter of putting on some annotations or something. If this approach is taken, I think such a PR would be reasonable.
